# List of dependecies for CSI snapshotter

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]


[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "=1.0.0" # Set this to exactly 1.0.0 until we can update test code to handle 1.1.0


# The dependency on external-provisioner should be removed with #60.
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
