# This YAML file shows how to deploy the snapshot controller

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: snapshot-controller
spec:
  serviceName: "snapshot-controller"
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-controller
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccount: snapshot-controller
      containers:
        - name: snapshot-controller
          # NOTE: replace with official image when released: quay.io/k8scsi/snapshot-controller:v2.0.0
          image: snapshot-controller:testbeta #quay.io/k8scsi/snapshot-controller:testbeta
          args:
            - "--v=5"
            - "--leader-election=false"
          imagePullPolicy: IfNotPresent #Always
